### ISSUE TITLE
Page: Text Block Element: Add a checkbox for users to indicate manual completion

### ISSUE THREAD

**Issue by mjsamberg** [TheFridayInstitute/studentslead#28]
Default text: "I've done this!" with option to customize.

**Comment by mjsamberg** [comment]
@adreier to provide default text.

**Comment by adreier** [comment]
@christinasimmons and I will finalize.

**Comment by mjsamberg** [comment]
@adreier @christinasimmons Have you had a chance to identify the default text yet?

**Comment by adreier** [comment]
Let's go with "I've done this!" for now.
