### ISSUE TITLE
Sections Module: Availability criteria

### ISSUE THREAD

**Issue by mjsamberg** [TheFridayInstitute/studentslead#29]
Availability criteria shold show, but not be obtrusive or large.

(Currently, section narrative is used to display availability criteria, should be moved elsewhere so section narrative could be phased out).

**Comment by christinasimmons** [comment]
(Notes from 3/6 meeting) Keep on main page but shorten to 1 line, shrink font, change from solid black to grayscale, and push to right. Make lock a mouseover too.
