### ISSUE TITLE
Page module: Add "In this Zone" checklist and "My Notes" to sidebar.

### ISSUE THREAD

**Issue by mjsamberg** [TheFridayInstitute/studentslead#30]
"In this zone" is an admin-settable text box at the unit level.

"My notes" is a textbox where a user can keep ongoing notes.

**Comment by mjsamberg** [comment]
@adreier @christinasimmons Should notes be per-page or global that a user would add to?

**Comment by adreier** [comment]
I'm imagining a "My Notes" field that lives at the bottom of the Action Plan. Can the display be per-page (i.e., not backfilling) but it aggregates the submissions at the bottom of the Action Plan?

**Comment by christinasimmons** [comment]
(Notes from 3/6 meeting)
Right rail order on every page:
In the Zone checklist
My Action Plan (only if there are Qs)
Notes
