### ISSUE TITLE
"home" breadcrumb link on static pages goes to section home, not site home

### ISSUE THREAD

**Issue by maday4** [TheFridayInstitute/studentslead#39]
At the static level (home, support, terms, faq, admin, and allies) "home" should go to https://studentslead.fi.ncsu.edu/#!/pages/home rather than https://studentslead.fi.ncsu.edu/#!/sections

**Comment by adreier** [comment]
If they're logged into the system, "Home" should always take them to https://studentslead.fi.ncsu.edu/#!/sections.  If they're not (i.e., a teacher needs to pass along the link to the FAQ to a principal, etc.) then it should go to https://studentslead.fi.ncsu.edu/#!/pages/home. Let me know if that doesn't work.

**Comment by maday4** [comment]
I find it confusing that I can't get back to the site home page if I go to the FAQ or Allies page (or anywhere else). Usually "Home" is a site's home page, not a sub-section home page. Maybe we could add another crumb for the course home page: Home (i.e., site) > Course > Zone > Sub page

**Comment by adreier** [comment]
Once you're registered, though, I consider the "site" home to be the "sections" page. It's comparable to the catalog page for our MOOC-Eds. Once you've made the sale (i.e., gotten people into the course) the home button should take you to the course landing page itself.

**Comment by adreier** [comment]
So rather than thinking of it as a site home page, we should consider it our marketing/registration page.
