### ISSUE TITLE
Login Failure text

### ISSUE THREAD

**Issue by adreier** [TheFridayInstitute/studentslead#4]
No indication how a login has failed. Expected to see something like "invalid password" or "email does not match anyone in the system" or something like that.

**Comment by mjsamberg** [comment]
@adreier This obscurity is deliberate and a recommended best practice - if someone is attempting to gain access to an account that's not theirs, an extra layer of security is to not give away that they have any information correct.

**Comment by adreier** [comment]
Okay, just seems really weird and I am not used to it.

**Comment by mjsamberg** [comment]
Revisit once rate-limiting is in place.
