### ISSUE TITLE
Display for Action Plan

### ISSUE THREAD

**Issue by mjsamberg** [TheFridayInstitute/studentslead#42]

**Comment by mjsamberg** [comment]
➤ Mark Samberg commented:
Does there need to be text above the plan with prompting?

**Comment by adreier** [comment]
@christinasimmons reviewing

**Comment by adreier** [comment]
I'm not sure what this issue is referring to at this point.

**Comment by mjsamberg** [comment]
➤ Mark Samberg commented:

https://app.asana.com/0/324967709993553/324967709993553 Is the wireframe for this anywhere?

**Comment by mjsamberg** [comment]
➤ Christina Simmons commented:

https://app.asana.com/0/18375306507461/18375306507461 and https://app.asana.com/0/18375306507439/18375306507439, there are no wires for this, but we did have a group phone call to discuss simple solutions to making this page more visually appealing. Do either of you recall where those notes were captured? They included simple things like adding in the zone icons, etc.

**Comment by mjsamberg** [comment]
➤ Christina Simmons commented:

Actually, here are the notes from that call:
Decisions:
    Use color blocks that appear elsewhere in the course.
    Add some of the personalization elements to this page.
    Use the zone icons (for Unit 2, take the 4 zone icons and make a bigger square.)
    Once the above are implemented, revisit look-and-feel.

**Comment by mjsamberg** [comment]
➤ Mark Samberg commented:

https://app.asana.com/0/324967709993553/324967709993553 https://app.asana.com/0/18375306507439/18375306507439 I added the card layout, but left the header as orange - becuase I didn't want to make it green/red because a lot of the action plan (two of the four zones in section 2) will be blank for most students.

**Comment by mjsamberg** [comment]
➤ Mark Samberg commented:

This is in dev

**Comment by mjsamberg** [comment]
➤ Christina Simmons commented:

This looks better. We could also consider adding in other personalization elements (when built), like a student's avatar next to the "My Action Plan" head and their chosen wallpaper as the background for the page.

We should also test what it looks like when print/save as PDF/email, etc. are in place.
