### ISSUE TITLE
Once logged in, you should be taken to course home page rather than catalog page

### ISSUE THREAD

**Issue by adreier** [TheFridayInstitute/studentslead#46]

**Comment by mjsamberg** [comment]
Unable to reproduce in Chrome, Safari, or Firefox. Is this after a timeout or on initial login?

**Comment by adreier** [comment]
This is when I'm already logged in and visit studentslead.fi.ncsu.edu (getting the catalog page still rather than the course landing page with the zones):
![screen shot 2017-03-09 at 2 55 08 pm](https://cloud.githubusercontent.com/assets/13201528/23767975/767da910-04d8-11e7-98d4-a3f3a2cfbd55.png)
