### ISSUE TITLE
Poll completion requirements should be per question instead of per-poll. Also, "view only" should not be an option for polls.

### ISSUE THREAD

**Issue by mjsamberg** [TheFridayInstitute/studentslead#47]

**Comment by adreier** [comment]
This should be the same issue (three middle ones are green), but want to make sure: https://dev-studentslead.fi.ncsu.edu/#!/page/10

**Comment by adreier** [comment]
Poll is marked as complete (OS X/Chrome) filling anything in: https://dev-studentslead.fi.ncsu.edu/#!/page/12
