### ISSUE TITLE
Add zone graphic thumbnail to the left of the page title

### ISSUE THREAD

**Issue by adreier** [TheFridayInstitute/studentslead#49]
To the left of "Tech Tools" here, as an example: 
![screen shot 2017-03-09 at 4 20 37 pm](https://cloud.githubusercontent.com/assets/13201528/23771317/8c944860-04e4-11e7-8543-4343cf578724.png)

**Comment by mjsamberg** [comment]
@adreier Reference #20. If the zone thumbnail appears in the breadcrumbs next to a progress bar to be added, should it appear again immediately below it in the page title?

**Comment by adreier** [comment]
If zone thumbnail is located there, it's totally fine.

**Comment by mjsamberg** [comment]
Closing this issue, will address via #20.
