### ISSUE TITLE
CAPTCHA images not visible - Mac/Chrome

### ISSUE THREAD

**Issue by adreier** [TheFridayInstitute/studentslead#5]
Just clicked I am not a robot and didn't have to do anything

**Comment by mjsamberg** [comment]
Did the behavior match expected per this blog (sometimes it will check without any interaction):
https://security.googleblog.com/2014/12/are-you-robot-introducing-no-captcha.html

**Comment by mjsamberg** [comment]
TL;DR Verison: https://youtu.be/jwslDn3ImM0

**Comment by adreier** [comment]
Yep -- very helpful. I had to do it on Firefox, so I'm glad it's just having to do more of FF rather than something being missing in Chrome.
