### ISSUE TITLE
External embedded videos are different sizes than internal ones

### ISSUE THREAD

**Issue by adreier** [TheFridayInstitute/studentslead#50]

**Comment by mjsamberg** [comment]
Embedding outside videos is strongly discouraged in this course. However, this is not a technical issue. @maday - if videos are absolutely necessary, wrap them as follows for a consistent look:

`<div class="row">
    <div class="col-xs-12 col-md-8 offset-md-2" ng-if="element.video_mp4.length||element.video_webm.length||element.video_ogg.length">
        <div class="embed-responsive embed-responsive-16by9">
            <div class="embed-responsive embed-responsive-21by9">
  <iframe class="embed-responsive-item" src="..."></iframe>
</div>
        </div>
    </div>
</div>`
