### ISSUE TITLE
Videos displaying as green when not completed

### ISSUE THREAD

**Issue by adreier** [TheFridayInstitute/studentslead#51]

**Comment by mjsamberg** [comment]
This is a setting in the admin panel - which video is it so that I can confirm that settings are working as expected.

**Comment by adreier** [comment]
Chelsea's story (you can see where I watched until)

![screen shot 2017-03-09 at 4 30 47 pm](https://cloud.githubusercontent.com/assets/13201528/23771665/e3bf7942-04e5-11e7-8575-389f117f8d57.png)

**Comment by adreier** [comment]
Also applies to videos on https://dev-studentslead.fi.ncsu.edu/#!/page/11 and https://dev-studentslead.fi.ncsu.edu/#!/page/12

**Comment by mjsamberg** [comment]
Platform is working as expected. Page 11 - course video was not set to enforce students to watch until the video is complete (@maday4, please check across all videos). Page 12 - video is a YouTube embed and the video is embedded in a text block - there is no way to get completion data for that video.

**Comment by maday4** [comment]
All of the embedded videos (except the YouTube embed) now wait to turn green until you have reached the end of the video. You can get around watching the whole video by dragging the video player progress cursor to the end of the progress bar, but I don't know if we care about that or not
