### ISSUE TITLE
Add text box when "other" is selected in a poll

### ISSUE THREAD

**Issue by adreier** [TheFridayInstitute/studentslead#54]
See Q2 here: https://dev-studentslead.fi.ncsu.edu/#!/page/8

**Comment by mjsamberg** [comment]
Exists for radio, need to add and figure out for dropdowns.

**Comment by mjsamberg** [comment]
@adreier @maday4 Please note that this change is moved to dev. In dev, and then in production, the "Other" option will need to be removed from the list of options and the "Display Other Option" checkbox will need to be checked.
