### ISSUE TITLE
"I've done this!" box from yellow to red

### ISSUE THREAD

**Issue by adreier** [TheFridayInstitute/studentslead#56]
@christinasimmons and I aren't wedded to this change -- we'd just like to see what it looks like vis-a-vis the current yellow. I actually began to like the yellow more as I moved through the pages, but it would be nice to see what red looks like.

**Comment by mjsamberg** [comment]
Here it is with the two reds from the palette. Question - will it be differentiated enough from the header below it that students won't miss it...

<img width="593" alt="screen shot 2017-03-16 at 1 18 56 pm" src="https://cloud.githubusercontent.com/assets/1527123/24009374/27367684-0a4b-11e7-9ce2-f2e51dd478ae.png">
<img width="594" alt="screen shot 2017-03-16 at 1 19 03 pm" src="https://cloud.githubusercontent.com/assets/1527123/24009373/27333320-0a4b-11e7-9464-7b18e6ee2153.png">

**Comment by adreier** [comment]
I definitely don't like the second one, but if you showed me the first one **prior** to me working through the pages I would have preferred it to the yellow. But, as I noted, I got pretty used to the yellow quickly.

What say you, @christinasimmons?

**Comment by christinasimmons** [comment]
@adreier @mjsamberg I prefer red option 1. It's consistent with the red > green functionality in the rest of the main column blocks, and the yellow was making the pages start to look a bit like a box of crayons. Mark, I share your concern about students possibly missing it, but I do think they'll catch on quickly and we can also test for this specifically.

**Comment by adreier** [comment]
Makes sense to me -- we discussed the crayons/starbursts/skittles fear yesterday. Let's go with the red, and we can always adjust if it seems to confuse.
