### ISSUE TITLE
Check-In Poll resulting in unintended message

### ISSUE THREAD

**Issue by adreier** [TheFridayInstitute/studentslead#60]
I was unable to replicate this myself, but both Christina and Lisa experienced it: "In Check In poll, pop-up box said “Please check this box if you want to proceed” (not sure which box it referred to) but the poll results still displayed and that box remained visible until I clicked away."

@christinasimmons -- can you let Mark know what device/OS you were using when this happened?

**Comment by christinasimmons** [comment]
@mjsamberg MacBook Pro, OS Sierra Version 10.12.3, Firefox 52.0.

**Comment by mjsamberg** [comment]
@christinasimmons Can you take a screenshot?

**Comment by christinasimmons** [comment]
@mjsamberg I wasn't able to recreate it just now but will try again later. It was specifically on this page for me: https://dev-studentslead.fi.ncsu.edu/#!/page/20
