### ISSUE TITLE
Different style of bullets

### ISSUE THREAD

**Issue by adreier** [TheFridayInstitute/studentslead#62]
The bullets here have a word doc feel to them (https://dev-studentslead.fi.ncsu.edu/#!/page/28) -- do you have a list of potential alternatives that we might use here (and potentially elsewhere)?

**Comment by mjsamberg** [comment]
University branding technically calls for this:

![screen shot 2017-03-16 at 2 14 24 pm](https://cloud.githubusercontent.com/assets/1527123/24012013/e0891c84-0a52-11e7-859c-c086d718527a.png)

**Comment by adreier** [comment]
Let's go with that
