### ISSUE TITLE
Icon fixes needed across course

### ISSUE THREAD

**Issue by christinasimmons** [TheFridayInstitute/studentslead#63]
@mjsamberg and @maday4: @adreier and I went through the course to look at all icons. Attached is a chart with all icon changes needed. We've included links to specific icons in Flat Icons. Please yell if you have any questions.
[MOOC-S Icons.docx](https://github.com/TheFridayInstitute/studentslead/files/856413/MOOC-S.Icons.docx)

**Comment by mjsamberg** [comment]
@maday4 If you want to take care of the page-block level icons, I'll take care of the platform ones. Just need to download the SVG and add to FortAwesome.

**Comment by maday4** [comment]
page-block level icons are done
