### ISSUE TITLE
Help page: Embed FAQs in page

### ISSUE THREAD

**Issue by christinasimmons** [TheFridayInstitute/studentslead#64]
On this page: https://dev-studentslead.fi.ncsu.edu/#!/pages/support

Instead of linking out to FAQs from this page, embed the FAQs here. Text changes to:

Looking for answers? Read the FAQs below.
[embed FAQs]
If you didn't find what you were looking for or you need to report a technical issue, please contact us!

Email us at studentslead@fi.ncsu.edu and a Friday Institute staff member will respond as soon as possible.

- @adreier and Christina

**Comment by mjsamberg** [comment]
@christinasimmons @adreier If we're recreating a page to add one additional line of text, do we still need a separate page, or can we just combine them and change the links/labels.

**Comment by christinasimmons** [comment]
Ideally we're combining them.

**Comment by mjsamberg** [comment]
So we can just do that?  Leave the label as support in the header, leave as two links at the bottom?

**Comment by christinasimmons** [comment]
Sorry, I don't follow? There's no direct link to the FAQ in the header or footer that I see. The text change we're suggesting for the Help page means the only link in the body of the Help page is to an email address.
