### ISSUE TITLE
How to accomodate memory quiz

### ISSUE THREAD

**Issue by maday4** [TheFridayInstitute/studentslead#73]
How can we replicate https://goo.gl/v4m1zY? I experimented with iframe embed -- no luck.

**Comment by adreier** [comment]
Hi Meghan -- I gave it a shot and I think it's okay, but let me know.

**Comment by maday4** [comment]
It's not responsive (I get scrollbars), but if you're ok with that we can go with it.

**Comment by adreier** [comment]
If @mjsamberg can figure out how to make it responsive that would be great, but I think it's fine for now.

**Comment by mjsamberg** [comment]
I did a little bit with the bootstrap code. It still scrolls... You could probably make the form shorter by removing the banner image.

**Comment by adreier** [comment]
Just changed the theme, which should make it shorter
