### ISSUE TITLE
Registration agree/disagree text too big for iPhone

### ISSUE THREAD

**Issue by maday4** [TheFridayInstitute/studentslead#9]
The "Strongly Disagree", "Disagree", etc. runs together on an iPhone screen (Safari). I'll email you a screen shot -- I keep getting an error when I try to upload to GitHub.

**Comment by mjsamberg** [comment]
![reg_on_iphone](https://cloud.githubusercontent.com/assets/1527123/23474405/b1a8aa24-fe81-11e6-918b-c59c46cbe8d2.PNG)

**Comment by maday4** [comment]
Looks great!
